### ISSUE TITLE
Sonar 4.5.1 fail to load sevntu plugin 1.12.0

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#341]
2014.12.16 15:59:30 INFO  web[o.s.s.p.DefaultServerFileSystem]  SonarQube home: /opt/sonarqube-4.5.1
2014.12.16 15:59:30 INFO  web[org.sonar.INFO]  Install plugins...
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin Findbugs / 3.1 / adc09c989cebc856d44239116a00ab0b602b0851
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin Duplications / 4.5.1 / 0c5e3bad51d43c05de47187d16831067bea16a3f
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin Checkstyle / 2.2 / c3154fc86f16ffa4f67b74731010fc555efe6180
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin PMD / 2.3 / 9edb9f91ef49475358c99bf8a25c8dd9061e95e7
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin Core / 4.5.1 / 0c5e3bad51d43c05de47187d16831067bea16a3f
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin Java / 2.7 / 2a940acd1dfec5be2825c83b16b91b9b3baaba26
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin Database Cleaner / 4.5.1 / 0c5e3bad51d43c05de47187d16831067bea16a3f
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin English Pack / 4.5.1 / 0c5e3bad51d43c05de47187d16831067bea16a3f
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin Design / 4.5.1 / 0c5e3bad51d43c05de47187d16831067bea16a3f
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin Email notifications / 4.5.1 / 0c5e3bad51d43c05de47187d16831067bea16a3f
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin Build Breaker / 1.1 / 86110f67a03bc54b348f8fbfd5890bffd91274fe
2014.12.16 15:59:30 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin SevNTU Checkstyle Sonar Extension Plugin / 1.12.0

2014.12.16 15:59:37 ERROR web[o.a.c.c.C.[.[.[/]]  Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
org.sonar.api.utils.SonarException: XML is not valid
        at org.sonar.api.rules.XMLRuleParser.parse(XMLRuleParser.java:113) ~[sonar-deprecated-4.5.1.jar:na]
        at org.sonar.api.rules.XMLRuleParser.parse(XMLRuleParser.java:79) ~[sonar-deprecated-4.5.1.jar:na]
        at com.github.sevntu.checkstyle.sonar.CheckstyleExtensionRepository.createRules(CheckstyleExtensionRepository.java:33) ~[na:na]
        at org.sonar.server.rule.DeprecatedRulesDefinition.define(DeprecatedRulesDefinition.java:89) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:45) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:98) ~[sonar-server-4.5.1.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1015) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1008) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:766) ~[picocontainer-2.14.3.jar:na]
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:91) ~[sonar-plugin-api-4.5.1.jar:na]
        at org.sonar.server.platform.ServerComponents$1.doPrivileged(ServerComponents.java:590) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:43) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.platform.ServerComponents.executeStartupTasks(ServerComponents.java:586) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:126) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:122) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.platform.Platform.doStart(Platform.java:81) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43) ~[sonar-server-4.5.1.jar:na]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973) [tomcat-embed-core-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467) [tomcat-embed-core-7.0.54.jar:7.0.54]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559) [tomcat-embed-core-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549) [tomcat-embed-core-7.0.54.jar:7.0.54]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_40]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
        at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: com.ctc.wstx.exc.WstxParsingException: Unexpected close tag </code>; expected </br>.
 at [row,col {unknown-source}]: [367,369]
        at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:614) ~[woodstox-core-lgpl-4.4.0.jar:4.4.0]
        at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:487) ~[woodstox-core-lgpl-4.4.0.jar:4.4.0]
        at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:472) ~[woodstox-core-lgpl-4.4.0.jar:4.4.0]
        at com.ctc.wstx.sr.BasicStreamReader.reportWrongEndElem(BasicStreamReader.java:3285) ~[woodstox-core-lgpl-4.4.0.jar:4.4.0]
        at com.ctc.wstx.sr.BasicStreamReader.readEndElem(BasicStreamReader.java:3212) ~[woodstox-core-lgpl-4.4.0.jar:4.4.0]
        at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2831) ~[woodstox-core-lgpl-4.4.0.jar:4.4.0]
        at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1073) ~[woodstox-core-lgpl-4.4.0.jar:4.4.0]
        at org.codehaus.staxmate.in.SMFlatteningCursor.getNext(SMFlatteningCursor.java:115) ~[staxmate-2.0.1.jar:na]
        at org.codehaus.staxmate.in.SMInputCursor.collectDescendantText(SMInputCursor.java:504) ~[staxmate-2.0.1.jar:na]
        at org.sonar.api.rules.XMLRuleParser.processRule(XMLRuleParser.java:140) ~[sonar-deprecated-4.5.1.jar:na]
        at org.sonar.api.rules.XMLRuleParser.parse(XMLRuleParser.java:108) ~[sonar-deprecated-4.5.1.jar:na]
        ... 35 common frames omitted

**Comment by romani** [comment]
fixed
