### ISSUE TITLE
Latest sources give that error in Eclipse-cs runtime 

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#342]
!MESSAGE cannot initialize module TreeWalker - Unable to instantiate ForbidReturnInFinalBlockCheck
!STACK 0
net.sf.eclipsecs.core.util.CheckstylePluginException: cannot initialize module TreeWalker - Unable to instantiate ForbidReturnInFinalBlockCheck
	at net.sf.eclipsecs.core.util.CheckstylePluginException.rethrow(CheckstylePluginException.java:66)
	at net.sf.eclipsecs.core.util.CheckstylePluginException.rethrow(CheckstylePluginException.java:77)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:166)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:300)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:171)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:401)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:618)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:597)
	at org.eclipse.core.internal.resources.Project.build(Project.java:114)
	at net.sf.eclipsecs.core.jobs.BuildProjectJob.run(BuildProjectJob.java:97)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Unable to instantiate ForbidReturnInFinalBlockCheck
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:183)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:174)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:310)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:146)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:142)
	... 17 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate ForbidReturnInFinalBlockCheck
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:148)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:177)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:174)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:162)
	... 21 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate ForbidReturnInFinalBlockCheckCheck
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.doMakeObject(PackageObjectFactory.java:104)
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:145)
	... 24 more

**Comment by romani** [comment]
will be fixed in 1.13 , it was a problem of bad build

**Comment by rdiachenko** [comment]
The problem is still present in 1.13.0

**Comment by romani** [comment]
confirmed - " Unable to instantiate ForbidReturnInFinalBlockCheckCheck".

file eclipse/workspace/.metadata/.log
```
!SUBENTRY 1 net.sf.eclipsecs.core 4 4 2015-06-09 11:42:37.088
!MESSAGE cannot initialize module TreeWalker - Unable to instantiate ForbidReturnInFinalBlockCheck
!STACK 0
net.sf.eclipsecs.core.util.CheckstylePluginException: cannot initialize module TreeWalker - Unable to instantiate ForbidReturnInFinalBlockCheck
	at net.sf.eclipsecs.core.util.CheckstylePluginException.rethrow(CheckstylePluginException.java:66)
	at net.sf.eclipsecs.core.util.CheckstylePluginException.rethrow(CheckstylePluginException.java:77)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:166)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:300)
	at net.sf.eclipsecs.core.builder.CheckstyleBuilder.build(CheckstyleBuilder.java:171)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Unable to instantiate ForbidReturnInFinalBlockCheck
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:183)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:174)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:310)
	at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:146)
	at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:142)
	... 14 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate ForbidReturnInFinalBlockCheck
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:148)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:177)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:174)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:162)
	... 18 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate ForbidReturnInFinalBlockCheckCheck
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.doMakeObject(PackageObjectFactory.java:104)
	at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:145)
	... 21 more
```

**Comment by romani** [comment]
that Exception mean that name of Check is defined incorrectly in config, please do:
```
-    <module name="ForbidReturnInFinalBlockCheck">
+    <module name="ForbidReturnInFinallyBlock">
```

name of check was changed, that is true.
