### ISSUE TITLE
Cannot set property 'annotationTargets' in module ForbidAnnotation to 'VARIABLE_DEF'

### ISSUE THREAD

**Issue by rdiachenko** [sevntu-checkstyle/sevntu.checkstyle#350]
```
<module name="ForbidAnnotation">
      <property name="severity" value="warning"/>
      <property name="annotationNames" value="Autowired"/>
      <property name="annotationTargets" value="VARIABLE_DEF"/>
</module>
```

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Cannot set property 'annotationTargets' in module ForbidAnnotation to 'VARIABLE_DEF': com.puppycrawl.tools.checkstyle.api.TokenTypes.getTokenId(Ljava/lang/String;)I
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:150)
        at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:170)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:171)
        at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:160)
        ... 28 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2170)
        at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2151)
        at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:439)
        at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:147)
```

<b>Reproduced on:</b>
checkstyle 6.7
sevntu-checkstyle 1.13.3

**Comment by rnveach** [comment]
Closing as not reproducable with current sevntu. Please reopen with steps to reproduce issue if it is still valid.
````
$ cat TestClass.java
public class TestClass {
    void method() {
    }
}

$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="com.github.sevntu.checkstyle.checks.annotation.ForbidAnnotation">
      <property name="severity" value="warning"/>
      <property name="annotationNames" value="Autowired"/>
      <property name="annotationTargets" value="VARIABLE_DEF"/>
</module>
    </module>
</module>

$ java -jar checkstyle-sevntu-nightly-2016-12-03-all.jar -c TestConfig.xml TestClass.java
Starting audit...
Audit done.
````
