### ISSUE TITLE
Sonar fails to start with 'Extension to Sonar Checkstyle Plugin 1.13.3'

### ISSUE THREAD

**Issue by rdiachenko** [sevntu-checkstyle/sevntu.checkstyle#359]
```
$ cd [SONAR_HOME]/extensions/plugins
$ wget https://github.com/sevntu-checkstyle/sevntu.checkstyle/raw/gh-pages/sonar/sevntu-checkstyle-sonar-plugin-1.13.3.jar
# restart Sonar
```

```
2015.06.18 11:13:49 INFO  web[o.s.s.p.ServerPluginJarsInstaller]  Deploy plugin SevNTU Checkstyle Sonar Extension Plugin / 1.13.3
2015.06.18 11:13:49 INFO  web[org.sonar.INFO]  Install plugins done: 496 ms
2015.06.18 11:13:49 INFO  web[o.s.s.p.RailsAppsDeployer]  Deploy Ruby on Rails applications
2015.06.18 11:13:49 INFO  web[o.s.j.s.AbstractDatabaseConnector]  Initializing Hibernate
2015.06.18 11:13:52 INFO  web[o.s.s.p.UpdateCenterClient]  Update center: http://update.sonarsource.org/update-center.properties (no proxy)
2015.06.18 11:13:52 INFO  web[org.sonar.INFO]  Code colorizer, supported languages: java
2015.06.18 11:13:52 INFO  web[o.s.s.n.NotificationService]  Notification service started (delay 60 sec.)
2015.06.18 11:13:52 INFO  web[o.s.s.s.IndexSynchronizer]  Starting DB to Index synchronization
2015.06.18 11:13:53 INFO  web[o.s.s.s.BaseIndex]  Index rules:rules has last update of Wed Dec 17 14:59:50 EST 2014
2015.06.18 11:13:53 INFO  web[o.s.s.s.BaseIndex]  Index rules:activeRules has last update of Wed Dec 17 13:46:33 EST 2014
2015.06.18 11:13:53 INFO  web[o.s.s.s.BaseIndex]  Index logs:sonarLogs has last update of Wed Dec 17 13:46:33 EST 2014
2015.06.18 11:13:54 INFO  web[o.s.s.s.IndexSynchronizer]  Synchronization done in 2046ms...
2015.06.18 11:13:54 INFO  web[org.sonar.INFO]  Deploy GWT plugins...
2015.06.18 11:13:54 INFO  web[org.sonar.INFO]  Deploy GWT plugins done: 0 ms
2015.06.18 11:13:54 INFO  web[org.sonar.INFO]  Load metrics...
2015.06.18 11:13:55 INFO  web[o.s.s.s.RegisterMetrics]  Cleaning quality gate conditions
2015.06.18 11:13:55 INFO  web[org.sonar.INFO]  Load metrics done: 474 ms
2015.06.18 11:13:55 INFO  web[o.s.s.s.RegisterDebtModel]  Register technical debt model...
2015.06.18 11:13:55 INFO  web[o.s.s.s.RegisterDebtModel]  Register technical debt model done: 22 ms
2015.06.18 11:13:55 INFO  web[org.sonar.INFO]  Register rules...
2015.06.18 11:13:57 INFO  web[org.sonar.INFO]  Register rules done: 1896 ms
2015.06.18 11:13:57 INFO  web[o.s.s.n.NotificationService]  Notification service stopped
2015.06.18 11:13:57 ERROR web[o.a.c.c.C.[.[.[/]]  Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
org.sonar.api.utils.SonarException: Invalid property type [REGEX]
        at org.sonar.api.rules.XMLRuleParser.type(XMLRuleParser.java:231) ~[sonar-deprecated-4.5.1.jar:na]
        at org.sonar.api.rules.XMLRuleParser.processParameter(XMLRuleParser.java:182) ~[sonar-deprecated-4.5.1.jar:na]
        at org.sonar.api.rules.XMLRuleParser.processRule(XMLRuleParser.java:158) ~[sonar-deprecated-4.5.1.jar:na]
        at org.sonar.api.rules.XMLRuleParser.parse(XMLRuleParser.java:108) ~[sonar-deprecated-4.5.1.jar:na]
        at org.sonar.api.rules.XMLRuleParser.parse(XMLRuleParser.java:79) ~[sonar-deprecated-4.5.1.jar:na]
        at com.github.sevntu.checkstyle.sonar.CheckstyleExtensionRepository.createRules(CheckstyleExtensionRepository.java:33) ~[na:na]
        at org.sonar.server.rule.DeprecatedRulesDefinition.define(DeprecatedRulesDefinition.java:89) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:45) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:98) ~[sonar-server-4.5.1.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1015) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1008) ~[picocontainer-2.14.3.jar:na]
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:766) ~[picocontainer-2.14.3.jar:na]
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:91) ~[sonar-plugin-api-4.5.1.jar:na]
        at org.sonar.server.platform.ServerComponents$1.doPrivileged(ServerComponents.java:590) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:43) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.platform.ServerComponents.executeStartupTasks(ServerComponents.java:586) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:126) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:122) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.platform.Platform.doStart(Platform.java:81) ~[sonar-server-4.5.1.jar:na]
        at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43) ~[sonar-server-4.5.1.jar:na]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973) [tomcat-embed-core-7.0.54.jar:7.0.54]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467) [tomcat-embed-core-7.0.54.jar:7.0.54]
```

Sonar version: 4.5.1
sonar-checkstyle-plugin version: 2.2

**Comment by romani** [comment]
will be released as 1.13.4

**Comment by romani** [comment]
release 1.13.4 is ready.

**Comment by rdiachenko** [comment]
Sonar gives the following error when trying to start it up with 1.13.4 (https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/gh-pages/sonar/sevntu-checkstyle-sonar-plugin-1.13.4.jar):

```
2015.06.22 06:33:13 ERROR web[o.a.c.c.C.[.[.[/]]  Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
java.lang.IllegalStateException: Unable to read plugin manifest from jar : /home/rdiachenko/work/test/sonar/sonarqube-4.5.4/extensions/plugins/sevntu-checkstyle-sonar-plugin-1.13.4.jar
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:115) ~[sonar-update-center-common-1.11.jar:na]
	at org.sonar.core.plugins.PluginJarInstaller.extractMetadata(PluginJarInstaller.java:64) ~[sonar-core-4.5.4.jar:na]
	at org.sonar.server.plugins.ServerPluginJarsInstaller.loadInstalledPlugins(ServerPluginJarsInstaller.java:87) ~[sonar-server-4.5.4.jar:na]
	at org.sonar.server.plugins.ServerPluginJarsInstaller.install(ServerPluginJarsInstaller.java:66) ~[sonar-server-4.5.4.jar:na]
	at org.sonar.server.plugins.ServerPluginRepository.start(ServerPluginRepository.java:49) ~[sonar-server-4.5.4.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1015) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1008) ~[picocontainer-2.14.3.jar:na]
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:766) ~[picocontainer-2.14.3.jar:na]
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92) ~[sonar-plugin-api-4.5.4.jar:na]
	at org.sonar.server.platform.Platform.startLevel2Container(Platform.java:106) ~[sonar-server-4.5.4.jar:na]
	at org.sonar.server.platform.Platform.init(Platform.java:73) ~[sonar-server-4.5.4.jar:na]
	at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:42) ~[sonar-server-4.5.4.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973) [tomcat-embed-core-7.0.54.jar:7.0.54]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467) [tomcat-embed-core-7.0.54.jar:7.0.54]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-7.0.54.jar:7.0.54]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559) [tomcat-embed-core-7.0.54.jar:7.0.54]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549) [tomcat-embed-core-7.0.54.jar:7.0.54]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_45]
	at java.util.zip.ZipFile.<init>(ZipFile.java:220) ~[na:1.8.0_45]
	at java.util.zip.ZipFile.<init>(ZipFile.java:150) ~[na:1.8.0_45]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_45]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[na:1.8.0_45]
	at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:110) ~[sonar-update-center-common-1.11.jar:na]
	... 30 common frames omitted
```

**Comment by rdiachenko** [comment]
@romani  I run ```deploy-all.sh``` on my local pc and tried to use a newly created ```gh-pages/sonar/sevntu-checkstyle-sonar-plugin-1.13.4.jar```. Works fine.

**Comment by romani** [comment]
please recheck 1.13.5 release binaries.

**Comment by rdiachenko** [comment]
everything looks fine
