### ISSUE TITLE
3:19:39 PM CheckStylePluginException: An error occurred while scanning a file.: An error occurred during a file scan.

### ISSUE THREAD

**Issue by Nikki1993** [sevntu-checkstyle/sevntu.checkstyle#408]
An error occurred during a file scan.
org.infernus.idea.checkstyle.exception.CheckStylePluginException: An error occurred during a file scan.
	at org.infernus.idea.checkstyle.exception.CheckStylePluginException.wrap(CheckStylePluginException.java:34)
	at org.infernus.idea.checkstyle.checker.CheckFilesThread.run(CheckFilesThread.java:43)
Caused by: java.lang.NoClassDefFoundError: com/github/sevntu/checkstyle/Utils
	at com.github.sevntu.checkstyle.checks.coding.AvoidModifiersForTypesCheck.visitToken(AvoidModifiersForTypesCheck.java:187)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:332)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:204)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.processAndAudit(CheckStyleChecker.java:64)
	at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:40)
	at org.infernus.idea.checkstyle.checker.FileScanner.lambda$checkPsiFile$12(FileScanner.java:90)
	at java.util.Optional.map(Optional.java:215)
	at org.infernus.idea.checkstyle.checker.FileScanner.checkPsiFile(FileScanner.java:90)
	at org.infernus.idea.checkstyle.checker.FileScanner.run(FileScanner.java:42)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:943)
	at org.infernus.idea.checkstyle.checker.CheckFilesThread.runFileScanner(CheckFilesThread.java:30)
	at org.infernus.idea.checkstyle.checker.AbstractCheckerThread.processFilesForModuleInfoAndScan(AbstractCheckerThread.java:113)
	at org.infernus.idea.checkstyle.checker.CheckFilesThread.run(CheckFilesThread.java:39)

Running latest Intellij IDEA 15.0.2 on ArchLinux with JDK 8. I am a bit lost why it doesn't work when I try to run it so could anyone point me out to the right direction?

**Comment by romani** [comment]
checkstyle is a library , we do not do any plugins, all of them supported by other teams.

please read http://checkstyle.sourceforge.net/report_issue.html#How_to_report_a_bug to see what issue report we expect.

mostlikely you need to file issue against https://github.com/jshiell/checkstyle-idea .

**Comment by romani** [comment]
> com.github.sevntu.checkstyle.checks.coding.AvoidModifiersForTypesCheck

hmm, `sevntu`, it is https://github.com/sevntu-checkstyle/sevntu.checkstyle , please go to sevntu project to open an issue and please make sure that you provide all details and version of used IntelijIdea checkstyle plugin and sevntu plugin.
