### ISSUE TITLE
exception in StaticMethodCandidate and EnumValueNameCheck on Checkstyle sources

### ISSUE THREAD

**Issue by romani** [sevntu-checkstyle/sevntu.checkstyle#429]
checks are disabled - https://github.com/checkstyle/checkstyle/commit/519c99902fd56123383e21f007ab69c55b16fd2e

`/checkstyle [master|✚ 1] $ mvn -X checkstyle:checkstyle`

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/rivanov/java/git-others/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:319)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:275)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:538)
	... 21 more
Caused by: java.lang.NullPointerException
	at com.github.sevntu.checkstyle.checks.naming.EnumValueNameCheck.visitToken(EnumValueNameCheck.java:180)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:363)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:478)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:305)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:181)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:339)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:309)
	... 24 more

```

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing /home/rivanov/java/git-others/checkstyle/checkstyle/src/main/java/com/puppycrawl/tools/checkstyle/Checker.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:319)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:275)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:252)
	at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
	... 24 more
Caused by: java.lang.NullPointerException
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.getIdentText(StaticMethodCandidateCheck.java:353)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.access$1500(StaticMethodCandidateCheck.java:66)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck$Frame$2.apply(StaticMethodCandidateCheck.java:833)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck$Frame$2.apply(StaticMethodCandidateCheck.java:830)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:675)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators.tryFind(Iterators.java:771)
	at com.google.common.collect.Iterables.tryFind(Iterables.java:670)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck$Frame.findEnumConstInFrame(StaticMethodCandidateCheck.java:836)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.findField(StaticMethodCandidateCheck.java:595)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.isStaticFieldOrLocalVariable(StaticMethodCandidateCheck.java:546)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.isExprAcceptable(StaticMethodCandidateCheck.java:422)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.isExprAcceptable(StaticMethodCandidateCheck.java:431)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.isExprAcceptable(StaticMethodCandidateCheck.java:431)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.isExprAcceptable(StaticMethodCandidateCheck.java:431)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.access$800(StaticMethodCandidateCheck.java:66)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck$1.apply(StaticMethodCandidateCheck.java:376)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck$1.apply(StaticMethodCandidateCheck.java:373)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:675)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators.tryFind(Iterators.java:771)
	at com.google.common.collect.Iterables.tryFind(Iterables.java:670)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.isFrameExpressionsAcceptable(StaticMethodCandidateCheck.java:379)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.checkFrame(StaticMethodCandidateCheck.java:331)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.checkFrame(StaticMethodCandidateCheck.java:327)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.checkFrame(StaticMethodCandidateCheck.java:327)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.checkFrame(StaticMethodCandidateCheck.java:327)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.checkFrame(StaticMethodCandidateCheck.java:327)
	at com.github.sevntu.checkstyle.checks.design.StaticMethodCandidateCheck.finishTree(StaticMethodCandidateCheck.java:237)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyEnd(TreeWalker.java:349)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:307)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:181)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:80)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:339)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:309)
	... 27 more

```

**Comment by Vladlis** [comment]
Exceptions were caused by usage of Checkstyle 6.16  which breaks TokenTypes compatibility https://github.com/checkstyle/checkstyle/issues/2997.
Since https://github.com/checkstyle/checkstyle/commit/bdd5e77dcf0da36ac0814f7433e377a2927a3d48 the issue in Checkstyle build is resolved: https://github.com/checkstyle/checkstyle/pull/3042

**Comment by romani** [comment]
merged.
