### ISSUE TITLE
NumericLiteralNeedsUnderscore fails sonar project analysis

### ISSUE THREAD

**Issue by cypai** [sevntu-checkstyle/sevntu.checkstyle#437]
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Property 'minHexSymbolLength' in module com.github.sevntu.checkstyle.checks.coding.NumericLiteralNeedsUnderscoreCheck does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:168)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:138)
	at org.sonar.plugins.checkstyle.CheckstyleExecutor.execute(CheckstyleExecutor.java:86)
	... 54 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property 'minHexSymbolLength' in module com.github.sevntu.checkstyle.checks.coding.NumericLiteralNeedsUnderscoreCheck does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:165)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:131)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:178)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:138)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:163)
```

**Comment by romani** [comment]
issue is closed
