### ISSUE TITLE
Initialization problem in CustomDeclarationOrder with eclipsecs 6.19 and eclipsecs-sevntu-plugin 1.21

### ISSUE THREAD

**Issue by KTannenberg** [sevntu-checkstyle/sevntu.checkstyle#459]
After updating checkstyle to latest version we encountered following problem:

a bit formatted ...../.metadata/.log :

```
...
!STACK 0
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Unable to instantiate 'CustomDeclarationOrder' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.blocks.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.coding.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.design.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.header.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.imports.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.indentation.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.javadoc.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.metrics.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.modifier.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.naming.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.regexp.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.sizes.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.whitespace.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.filters.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.annotation.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.coding.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.design.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.naming.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.sizes.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.whitespace.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.CustomDeclarationOrder
, com.github.sevntu.checkstyle.grammars.CustomDeclarationOrder
, com.github.sevntu.checkstyle.CustomDeclarationOrder, CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.annotation.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.blocks.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.coding.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.design.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.header.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.imports.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.indentation.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.javadoc.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.metrics.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.modifier.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.naming.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.regexp.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.sizes.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.whitespace.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.filters.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.annotation.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.coding.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.design.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.naming.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.sizes.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.whitespace.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.grammars.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.CustomDeclarationOrderCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
    at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:407)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:138)
    at net.sf.eclipsecs.core.builder.CheckerFactory.createCheckerInternal(CheckerFactory.java:292)
    at net.sf.eclipsecs.core.builder.CheckerFactory.createChecker(CheckerFactory.java:128)
    at net.sf.eclipsecs.core.builder.Auditor.runAudit(Auditor.java:142)
    at net.sf.eclipsecs.core.builder.CheckstyleBuilder.handleBuildSelection(CheckstyleBuilder.java:300)
    at net.sf.eclipsecs.core.jobs.RunCheckstyleOnFilesJob.runInWorkspace(RunCheckstyleOnFilesJob.java:116)
    at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'CustomDeclarationOrder' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.blocks.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.coding.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.design.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.header.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.imports.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.indentation.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.javadoc.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.metrics.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.modifier.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.naming.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.regexp.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.sizes.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.whitespace.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.checks.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.filters.CustomDeclarationOrder
, com.puppycrawl.tools.checkstyle.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.annotation.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.coding.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.design.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.naming.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.sizes.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.whitespace.CustomDeclarationOrder
, com.github.sevntu.checkstyle.checks.CustomDeclarationOrder
, com.github.sevntu.checkstyle.grammars.CustomDeclarationOrder
, com.github.sevntu.checkstyle.CustomDeclarationOrder, CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.annotation.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.blocks.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.coding.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.design.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.header.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.imports.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.indentation.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.javadoc.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.metrics.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.modifier.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.naming.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.regexp.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.sizes.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.whitespace.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.checks.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.filters.CustomDeclarationOrderCheck
, com.puppycrawl.tools.checkstyle.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.annotation.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.coding.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.design.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.naming.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.sizes.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.whitespace.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.checks.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.grammars.CustomDeclarationOrderCheck
, com.github.sevntu.checkstyle.CustomDeclarationOrderCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
    at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:99)
    at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:153)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:138)
    at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:402)
    ... 8 more

```

This problem is reproducible on Eclipse 4.6 Neon with following combinations of EclipseCs and SevntuChecks:
1. EclipseCs 6.19 and SevntuChecks 1.21
2. EclipseCs 6.16 and SevntuChecks 1.21
3. EclipseCs 6.19 and SevntuChecks 1.20
   Only working combination is EclipseCs 6.16 and SevntuChecks 1.20

Similar problem exists with Eclipse 4.4 Luna (checked only with EclipseCs 6.19 and SevntuChecks 1.21), but in this case no error message is seen in log and all checks doesn't work correctly, see attached screenshot.
![luna-4 4](https://cloud.githubusercontent.com/assets/1444439/16380715/911d47f2-3c70-11e6-8169-1cfd97c41594.png)

**Comment by vorburger** [comment]
Just a hunch, but this MAY be the same as https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/460 .. although normally you should see a ClassNotFoundException re. ANTLR somewhere in the error log (in what you have shown above there isn't), but maybe that got swallowed somewhere..

**Comment by romani** [comment]
it is also strange why `com.puppycrawl.tools.checkstyle` and `com.github.sevntu.checkstyle` packages are listed twice .... smth is wrong...

**Comment by ChristophLu** [comment]
This also applies for this setup:
* Eclipse Checkstyle Plug-in (6.19.1.201607051943)
* Extension for eclipse-cs plugin with additional Checks (1.21.0)
* Eclipse Neon 4.6.0

The problem is, that no other checks are performed. A "semi"-solution would be to perform as many checks as possible and produce an error for the failing ones. But since this problem occurs, I'm not able to check the code in Eclipse.

@vorburger In my case, no errors are shown for ANTLR. It is only the one posted above.

**Comment by ChristophLu** [comment]
@romani I think that those two packages are not listed twice. At first, it searches for a class called `CustomDeclarationOrder` and then it searches for `CustomDeclarationOrderCheck`. But since the correct class name (`com.github.sevntu.checkstyle.checks.coding.CustomDeclarationOrderCheck`) is listes, there must be a problem with the `moduleClassLoader` in `PackageObjectFactory`.

**Comment by romani** [comment]
this is not a problem on Eclipse-cs 7.3.0 and sevntu 1.23.1 .
