### ISSUE TITLE
ForbidCCommentsInMethods incompatible with checkstyle 8.7

### ISSUE THREAD

**Issue by kemitix** [sevntu-checkstyle/sevntu.checkstyle#635]
In checkstyle 8,7 the guava code library has been removed. However, the sevntu check ForbidCCommentsInMethods uses this library.
```
Caused by: java.lang.NoSuchMethodError: com.puppycrawl.tools.checkstyle.api.FileContents.getBlockComments()Lcom/google/common/collect/ImmutableMap;
	at com.github.sevntu.checkstyle.checks.coding.ForbidCCommentsInMethodsCheck.beginTree(ForbidCCommentsInMethodsCheck.java:66)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyBegin(TreeWalker.java:388)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:359)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:203)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:83)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:319)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:289)
```

Using sevntu 1.26.0 and checkstyle 8.7.

**Comment by kemitix** [comment]
Happy to look at updating the check to not use guava.

**Comment by kemitix** [comment]
I see from 632c227, that sevntu is compatible eclipse-cs rather than checkstyle directly, thus follows that versions available for that. The latest version is which is 8.5.1.

Does that mean that sevntu can't be used with checkstyle 8,7 until eclipse-cs is updated? Or am I completely misunderstanding the relationships here.?

**Comment by rnveach** [comment]
> Does that mean that sevntu can't be used with checkstyle 8,7 until eclipse-cs is updated?

Yes this is correct.
Besides sevntu, this project also has an eclipse-cs version of sevntu. Since we broke compatibility in main project, if sevntu doesn't match eclipse-cs it will see similar errors that you have found.

I recommend downgrading checkstyle project for sevntu run.
See https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L224 and https://github.com/checkstyle/checkstyle/blob/master/pom.xml#L558-L578 .

**Comment by rnveach** [comment]
> ForbidCCommentsInMethods uses this library.

Technically it doesn't use the library. It is indirectly using the guava API because that is what the method used to return. We don't use the guava API in sevntu as an import as we go directly to calling another method on it. So it is just a compile dependency. Once checkstyle version is upgraded, problem will disappear on it's own with no code changes.

**Comment by romani** [comment]
Ones https://github.com/checkstyle/eclipse-cs/issues/1 is released, we will make new sevntu version base on 8.7 versions to avoid such problem.

**Comment by kemitix** [comment]
Thanks for the feedback,
