### ISSUE TITLE
Fixes for release

### ISSUE THREAD

**Issue by rnveach** [sevntu-checkstyle/sevntu.checkstyle#638]
1)
Move external repositories outside of project folder and place in /temp directory.
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/d024576c90a4e353c6e1c30882352b6ac2245dc2/deploy.sh#L27-L36
https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/SevNTU-plugin-for-EclipseCS-plugin-compilation
Step 2.

2)
Don't delete and re-create external repositories . Do fetch, reset, and remove extra files.
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/d024576c90a4e353c6e1c30882352b6ac2245dc2/deploy.sh#L27

3)
https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-release-sevntu.checkstyle
Before 2.1 we must do fetch and create new branch off origin/master .

4)
https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-release-sevntu.checkstyle
Step 2 (do compilation of eclipse-CS plugin) needs to be merged (partially or fully) to step 4's deploy-all . If it is missed, error results in build.
````
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from eclipsecs-sevntu-plugin 1.27.0 to bundle net.sf.eclipsecs.checkstyle 0.0.0.; Unable to satisfy dependency from eclipsecs-sevntu-plugin 1.27.0 to bundle net.sf.eclipsecs.core 0.0.0.; Unable to satisfy dependency from eclipsecs-sevntu-plugin 1.27.0 to bundle net.sf.eclipsecs.ui 0.0.0.; No solution found because the problem is unsatisfiable.] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from eclipsecs-sevntu-plugin 1.27.0 to bundle net.sf.eclipsecs.checkstyle 0.0.0.; Unable to satisfy dependency from eclipsecs-sevntu-plugin 1.27.0 to bundle net.sf.eclipsecs.core 0.0.0.; Unable to satisfy dependency from eclipsecs-sevntu-plugin 1.27.0 to bundle net.sf.eclipsecs.ui 0.0.0.; No solution found because the problem is unsatisfiable.]
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from eclipsecs-sevntu-plugin 1.27.0 to bundle net.sf.eclipsecs.checkstyle 0.0.0.; Unable to satisfy dependency from eclipsecs-sevntu-plugin 1.27.0 to bundle net.sf.eclipsecs.core 0.0.0.; Unable to satisfy dependency from eclipsecs-sevntu-plugin 1.27.0 to bundle net.sf.eclipsecs.ui 0.0.0.; No solution found because the problem is unsatisfiable.]
    at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.newResolutionException(AbstractResolutionStrategy.java:98)
    at org.eclipse.tycho.p2.util.resolution.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
    at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:63)
    at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:166)
    at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:103)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.doResolveDependencies(P2DependencyResolver.java:352)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.resolveDependencies(P2DependencyResolver.java:325)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:107)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:75)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    ... 11 more
````

**Comment by rnveach** [comment]
5.
https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/SevNTU-plugin-for-EclipseCS-plugin-compilation
Step 2.
Swap `git` url for https where possible.

Changes done already:
https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/How-to-release-sevntu.checkstyle/_compare/6b9910d8df138787b03f0f38c453a16c2ed2c1f0...c6e58f8c2fdbe075b60753d63e10ab016d04cb58

https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/SevNTU-plugin-for-EclipseCS-plugin-compilation/_compare/d6537755c0cbdccf66e0f8a382bad0e039a29e21...3e4538833a56174c50185b450448394c93c9af7a

**Comment by rnveach** [comment]
One final thought.
Is there a reason we can't use https://github.com/checkstyle/contribution/tree/master/releasenotes-builder to build the release notes for sevntu. It should also be able to handle the social media postings.

**Comment by romani** [comment]
@rnveach , yes , all that could be beneficial, eclipse-cs build is already in travis.

**Comment by rnveach** [comment]
> posting to social is still not used by me as there was problems and it not clear for me how to organize all that passwords .... it is doable. 

I see no issues in contributions for it. Please create some with any thoughts on what you think should be done.

**Comment by romani** [comment]
there is https://github.com/checkstyle/checkstyle/issues/3365 , I still do not know exact plan on how to make it secure as password could be shown in logs, and release process is still interactive (require passwords typing)

**Comment by rnveach** [comment]
7.
https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/SevNTU-plugin-for-EclipseCS-plugin-compilation
> Checksout to latest stable version (in example case it is 8.7.0) : 

Checkout should be done based on what sevntu-checks defines in its POM.

**Comment by rnveach** [comment]
> Swap git url for https where possible.
https://github.com/checkstyle/eclipse-cs.git

So I didn't realize but cloning from https requires you to give your credentials everytime you push back to the https.
The main reason I was avoiding ssh cloning/pushing is because LUbuntu fails on public keys with the SSH. It turns out you have to configure LUbuntu to get around this as it doesn't support it by default.

**Comment by rnveach** [comment]
Some minor improvements to script.

Confirm release numbers before continuing (display and pause until enter).
Examine deploy to maven to remove retesting. Other sections already tested everything.
Automate making release big text. (Edit tag, add description, publish release) - section 8.2
Automate social network. - section 9

Whole section 6 can't be automated?

**Comment by romani** [comment]
> Whole section 6 can't be automated?

it can be automated, just make sure you clone such repos by ssh , do `sed` substitution, push changes to remote (without PR).
