### ISSUE TITLE
Breaking change in CS-8.21 results in java.lang.Error

### ISSUE THREAD

**Issue by pzygielo** [sevntu-checkstyle/sevntu.checkstyle#747]
`/var/tmp $ javac f.java`
[empty]

`/var/tmp $ cat f.java`
```java
public class f {
}
```

`/var/tmp $ cat config.xml`
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8" />
    <property name="severity" value="warning" />
    <property name="fileExtensions" value="java, properties, xml" />
    <module name="TreeWalker">
        <module name="EmptyPublicCtorInClassCheck" />
    </module>
</module>
```
For Linux users:

`/var/tmp $ java -classpath sevntu-checks-1.33.0.jar:checkstyle-8.21-all.jar com.puppycrawl.tools.checkstyle.Main -c config.xml f.java`
```
Starting audit...
Exception in thread "main" java.lang.Error: Error was thrown while processing f.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:315)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:220)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:392)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:315)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:180)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:119)
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.puppycrawl.tools.checkstyle.api.DetailAST, but class was expected
	at com.github.sevntu.checkstyle.checks.coding.EmptyPublicCtorInClassCheck.visitToken(EmptyPublicCtorInClassCheck.java:197)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:363)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:470)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:304)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:162)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:332)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
	... 5 more
```
_Describe what you expect in detail._
I didn't expect `java.lang.Error`, but rather audit to complete, like for
`java -cp sevntu-checks-1.33.0.jar:checkstyle-8.20-all.jar com.puppycrawl.tools.checkstyle.Main -c checkstyle.xml f.java`
```
Starting audit...
Audit done.
```

**Comment by pzygielo** [comment]
GitHub suggested related issue https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/745#issuecomment-495997824 which is open, so closing this one.
