### ISSUE TITLE
sevntu-checkstyle-maven-plugin: duplicate checkstyle_packages.xml file

### ISSUE THREAD

**Issue by rnveach** [sevntu-checkstyle/sevntu.checkstyle#766]
Identified when reviewing changes at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/765 ,

The only source/resource we provide within `sevntu-checkstyle-maven-plugin` plugin is `checkstyle_packages.xml` which is located at https://github.com/sevntu-checkstyle/sevntu.checkstyle/tree/master/sevntu-checkstyle-maven-plugin/src/main/resources .
This is the same file inside `sevntu_checks` at https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checks/src/main/resources/checkstyle_packages.xml .

Since we are including sevntu dependency, which has `checkstyle_packages.xml` included by default, why does `sevntu-checkstyle-maven-plugin` need to duplicate the same XML file?
Can we remove this file?

**Comment by rnveach** [comment]
@romani I am also wondering why we even need this plugin if we remove this file and the project provides no other custom sources/resources of it's own. If we can use the normal `checkstyle-maven-plugin` for sevntu, I think we should consider deprecating the plugin so we don't need to maintain it anymore.

@rdiachenko Is it possible you can help us look into this too?
You seem well versed with plugin management so far.

**Comment by rnveach** [comment]
https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/master/sevntu-checkstyle-maven-plugin/src/main/resources/checkstyle_packages.xml#L17
`sevntu-checkstyle-maven-plugin`'s file does include checkstyle packages, but checkstyle doesn't need its own packages since we know and load them by default. Maybe at some point, when checkstyle required it's packages listed it only loaded the first package file it found?

**Comment by rdiachenko** [comment]
@rnveach , currently checkstyle loads all `checkstyle_packages.xml` found in classpath: https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/PackageNamesLoader.java#L143. So, in theory if we include `sevntu-checks` dependency instead of the maven extension directly to the main plugin, it should work. As a quick attempt I tried the following:
```
~/work/workspace/checkstyle [master ↑·78|✚ 1] $ git diff
diff --git a/pom.xml b/pom.xml
index 31a5d8c39..1055391e2 100644
--- a/pom.xml
+++ b/pom.xml
@@ -552,8 +552,8 @@
         <dependencies>
           <dependency>
             <groupId>com.github.sevntu-checkstyle</groupId>
-            <artifactId>sevntu-checkstyle-maven-plugin</artifactId>
-            <version>${maven.sevntu.checkstyle.plugin.version}</version>
+            <artifactId>sevntu-checks</artifactId>
+            <version>1.34.1</version>
           </dependency>
           <dependency>
             <groupId>com.puppycrawl.tools</groupId>
```
```
~/work/workspace/checkstyle [master ↑·78|✚ 1] $ mvn clean verify
...
[INFO] Results:
[INFO] 
[INFO] Tests run: 189, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.0:check (sevntu-checkstyle-check) @ checkstyle ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.4:check (default-check) @ checkstyle ---
[INFO] Loading execution data file /home/rdiachenko/work/workspace/checkstyle/target/jacoco.exec
[INFO] Analyzed bundle 'checkstyle' with 531 classes
[INFO] All coverage checks have been met.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (verify) @ checkstyle ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks

main:

execute:
     [echo] Checkstyle started (checkstyle_checks.xml): 10/07/2019 10:32:45 PM
[checkstyle] Running Checkstyle  on 1084 files
     [echo] Checkstyle finished (checkstyle_checks.xml) : 10/07/2019 10:33:24 PM
     [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 10/07/2019 10:32:45 PM
[checkstyle] Running Checkstyle  on 1819 files
     [echo] Checkstyle finished (checkstyle_non_main_files_checks.xml): 10/07/2019 10:33:24 PM
     [echo] Checkstyle started (checkstyle_resources_checks.xml): 10/07/2019 10:32:45 PM
[checkstyle] Running Checkstyle  on 1586 files
     [echo] Checkstyle finished (checkstyle_resources_checks.xml): 10/07/2019 10:33:24 PM
[INFO] Executed tasks
[INFO]
...
[INFO] Scanning classes for violations...
[INFO] Scanned 1769 class file(s) for forbidden API invocations (in 1.23s), 0 error(s).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:23 min
[INFO] Finished at: 2019-07-10T22:34:40+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by romani** [comment]
Let's do this step by step:
I release sevntu;
We update all our projects to not use maven plugin;
If all works fine, we remove maven plugin from sevntu repo

**Comment by romani** [comment]
@rdiachenko , release is done.
Please help us to remove usage of maven plugin from samples and from main checkstyle repo.

**Comment by rdiachenko** [comment]
Checked that `sevntu-checkstyle-maven-plugin` can be replaced with `sevntu-checks` dependency directly inside `maven-checkstyle-plugin`.
1. Update dependency versions and run `mvn clean verify` against checkstyle project
```
~/work/workspace/checkstyle [master|✚ 1] $ git diff
diff --git a/pom.xml b/pom.xml
index 31a5d8c39..9315d405d 100644
--- a/pom.xml
+++ b/pom.xml
@@ -201,9 +201,9 @@
     <powermock.version>2.0.2</powermock.version>
     <saxon.version>9.9.1-4</saxon.version>
     <maven.checkstyle.plugin.version>3.1.0</maven.checkstyle.plugin.version>
-    <maven.sevntu.checkstyle.plugin.version>1.34.1</maven.sevntu.checkstyle.plugin.version>
+    <maven.sevntu.checkstyle.plugin.version>1.35.0</maven.sevntu.checkstyle.plugin.version>
     <maven.sevntu-checkstyle-check.checkstyle.version>
-      8.18
+      8.20
     </maven.sevntu-checkstyle-check.checkstyle.version>
     <maven.versions.plugin.version>2.7</maven.versions.plugin.version>
     <java.version>1.8</java.version>
```
```
~/work/workspace/checkstyle [master|✚ 1] $ mvn clean verify
...
[INFO] Results:
[INFO] 
[INFO] Tests run: 189, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.0:check (sevntu-checkstyle-check) @ checkstyle ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.4:check (default-check) @ checkstyle ---
[INFO] Loading execution data file /home/rdiachenko/work/workspace/checkstyle/target/jacoco.exec
[INFO] Analyzed bundle 'checkstyle' with 531 classes
[INFO] All coverage checks have been met.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (verify) @ checkstyle ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks

main:

execute:
     [echo] Checkstyle started (checkstyle_checks.xml): 17/07/2019 11:30:37 PM
[checkstyle] Running Checkstyle  on 1084 files
     [echo] Checkstyle finished (checkstyle_checks.xml) : 17/07/2019 11:31:13 PM
     [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 17/07/2019 11:30:37 PM
[checkstyle] Running Checkstyle  on 1819 files
     [echo] Checkstyle finished (checkstyle_non_main_files_checks.xml): 17/07/2019 11:31:13 PM
     [echo] Checkstyle started (checkstyle_resources_checks.xml): 17/07/2019 11:30:37 PM
[checkstyle] Running Checkstyle  on 1586 files
     [echo] Checkstyle finished (checkstyle_resources_checks.xml): 17/07/2019 11:31:13 PM
[INFO] Executed tasks
...
[INFO] Scanned 1769 class file(s) for forbidden API invocations (in 1.21s), 0 error(s).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:56 min
[INFO] Finished at: 2019-07-17T23:32:16+01:00
[INFO] ------------------------------------------------------------------------
```
2. Use `sevntu-checks` dependency instead of `sevntu-checkstyle-maven-plugin` and run `mvn clean verify` against checkstyle project
```
~/work/workspace/checkstyle [master|✚ 1] $ git diff
diff --git a/pom.xml b/pom.xml
index 31a5d8c39..baa4a3646 100644
--- a/pom.xml
+++ b/pom.xml
@@ -201,9 +201,9 @@
     <powermock.version>2.0.2</powermock.version>
     <saxon.version>9.9.1-4</saxon.version>
     <maven.checkstyle.plugin.version>3.1.0</maven.checkstyle.plugin.version>
-    <maven.sevntu.checkstyle.plugin.version>1.34.1</maven.sevntu.checkstyle.plugin.version>
+    <maven.sevntu.checkstyle.plugin.version>1.35.0</maven.sevntu.checkstyle.plugin.version>
     <maven.sevntu-checkstyle-check.checkstyle.version>
-      8.18
+      8.20
     </maven.sevntu-checkstyle-check.checkstyle.version>
     <maven.versions.plugin.version>2.7</maven.versions.plugin.version>
     <java.version>1.8</java.version>
@@ -552,7 +552,7 @@
         <dependencies>
           <dependency>
             <groupId>com.github.sevntu-checkstyle</groupId>
-            <artifactId>sevntu-checkstyle-maven-plugin</artifactId>
+            <artifactId>sevntu-checks</artifactId>
             <version>${maven.sevntu.checkstyle.plugin.version}</version>
           </dependency>
           <dependency>
```
```
~/work/workspace/checkstyle [master|✚ 1] $ mvn clean verify
...
[INFO] Results:
[INFO]
[INFO] Tests run: 189, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-checkstyle-plugin:3.1.0:check (sevntu-checkstyle-check) @ checkstyle ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.4:check (default-check) @ checkstyle ---
[INFO] Loading execution data file /home/rdiachenko/work/workspace/checkstyle/target/jacoco.exec
[INFO] Analyzed bundle 'checkstyle' with 531 classes
[INFO] All coverage checks have been met.
[INFO]
[INFO] --- maven-failsafe-plugin:2.22.2:verify (verify) @ checkstyle ---
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (ant-phase-verify) @ checkstyle ---
[INFO] Executing tasks

main:

execute:
     [echo] Checkstyle started (checkstyle_checks.xml): 17/07/2019 11:14:08 PM
[checkstyle] Running Checkstyle  on 1084 files
     [echo] Checkstyle finished (checkstyle_checks.xml) : 17/07/2019 11:15:10 PM
     [echo] Checkstyle started (checkstyle_non_main_files_checks.xml): 17/07/2019 11:14:08 PM
[checkstyle] Running Checkstyle  on 1819 files
     [echo] Checkstyle finished (checkstyle_non_main_files_checks.xml): 17/07/2019 11:15:10 PM
     [echo] Checkstyle started (checkstyle_resources_checks.xml): 17/07/2019 11:14:08 PM
[checkstyle] Running Checkstyle  on 1586 files
     [echo] Checkstyle finished (checkstyle_resources_checks.xml): 17/07/2019 11:15:10 PM
[INFO] Executed tasks
...
[INFO] Scanned 1769 class file(s) for forbidden API invocations (in 1.37s), 0 error(s).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:20 min
[INFO] Finished at: 2019-07-17T23:16:12+01:00
[INFO] ------------------------------------------------------------------------
```
3. Both builds were successful, check that the diff between resulted configurations is empty
```
~/work/workspace/checkstyle [master|✚ 1] $ diff target-sevntu/checkstyle-checker.xml target-sevntu-maven/checkstyle-checker.xml 
~/work/workspace/checkstyle [master|✚ 1] $
```
4. Also, got the same exception with commented out `sevntu-checkstyle-maven-plugin` or explicit `sevntu-checks` inside the main maven plugin:
```
[INFO] --- maven-checkstyle-plugin:3.1.0:check (sevntu-checkstyle-check) @ checkstyle ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:16 min
[INFO] Finished at: 2019-07-18T00:01:51+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (sevntu-checkstyle-check) on project checkstyle: Failed during checkstyle configuration: cannot initialize module TreeWalker - cannot initialize module StaticMethodCandidate - Unable to instantiate 'StaticMethodCandidate' class, it is also not possible to instantiate it as .StaticMethodCandidate, StaticMethodCandidateCheck, .StaticMethodCandidateCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
```

**Comment by rdiachenko** [comment]
I also tried to use checkstyle 8.21 and sevntu-checks 1.35.0 and got expected exception due to broken compatibility in checkstyle 8.21:
```
~/work/workspace/checkstyle [master|✚ 1] $ git diff
diff --git a/pom.xml b/pom.xml
index 31a5d8c39..d2db2471c 100644
--- a/pom.xml
+++ b/pom.xml
@@ -201,9 +201,9 @@
     <powermock.version>2.0.2</powermock.version>
     <saxon.version>9.9.1-4</saxon.version>
     <maven.checkstyle.plugin.version>3.1.0</maven.checkstyle.plugin.version>
-    <maven.sevntu.checkstyle.plugin.version>1.34.1</maven.sevntu.checkstyle.plugin.version>
+    <maven.sevntu.checkstyle.plugin.version>1.35.0</maven.sevntu.checkstyle.plugin.version>
     <maven.sevntu-checkstyle-check.checkstyle.version>
-      8.18
+      8.21
     </maven.sevntu-checkstyle-check.checkstyle.version>
     <maven.versions.plugin.version>2.7</maven.versions.plugin.version>
     <java.version>1.8</java.version>
@@ -552,7 +552,7 @@
         <dependencies>
           <dependency>
             <groupId>com.github.sevntu-checkstyle</groupId>
-            <artifactId>sevntu-checkstyle-maven-plugin</artifactId>
+            <artifactId>sevntu-checks</artifactId>
             <version>${maven.sevntu.checkstyle.plugin.version}</version>
           </dependency>
           <dependency>
```
```
~/work/workspace/checkstyle [master|✚ 1] $ mvn clean verify
...
[INFO] Results:
[INFO]
[INFO] Tests run: 189, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-checkstyle-plugin:3.1.0:check (sevntu-checkstyle-check) @ checkstyle ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:17 min
[INFO] Finished at: 2019-07-17T23:09:52+01:00
[INFO] ------------------------------------------------------------------------
...
Exception in thread "main" java.lang.Error: Error was thrown while processing /home/rdiachenko/work/workspace/checkstyle/src/it/java/org/checkstyle/checks/imports/ImportOrderTest.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:315)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:220)
	at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:247)
	at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:537)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.puppycrawl.tools.checkstyle.api.DetailAST, but class was expected
	at com.github.sevntu.checkstyle.checks.coding.EmptyPublicCtorInClassCheck.visitToken(EmptyPublicCtorInClassCheck.java:197)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:363)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:470)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:304)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:162)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:85)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:332)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
	... 25 more
```

**Comment by romani** [comment]
Please send PRs to all our projects to remove sevntu  maven plugin.
After merge, we can delete maven plugin from repo

**Comment by rdiachenko** [comment]
All current usages:
* checkstyle organization - https://github.com/search?q=org%3Acheckstyle+sevntu-checkstyle-maven-plugin&type=Code
* sevntu-checkstyle organization - https://github.com/search?q=org%3Asevntu-checkstyle+sevntu-checkstyle-maven-plugin&type=Code

**Comment by rdiachenko** [comment]
Resolution notes:
- `sevntu-checkstyle-maven-plugin` is redundant and not needed, `sevntu-checks` dependency can be used directly in `maven-checkstyle-plugin` plugin configuration
- `sevntu-checkstyle-maven-plugin` was removed and not supported anymore

**!!MIGRATION!!** replace `sevntu-checkstyle-maven-plugin` with `sevntu-checks` within `maven-checkstyle-plugin` configuration, that is it (e.g.: https://github.com/checkstyle/sonar-checkstyle/pull/237/files#diff-600376dffeb79835ede4a0b285078036R301)

**Comment by romani** [comment]
All fixes are merged.
