### ISSUE TITLE
PreferMethodReference fails with Java 14 switch expression

### ISSUE THREAD

**Issue by jdussouillez** [sevntu-checkstyle/sevntu.checkstyle#918]
`PreferMethodReference` fails with Java 14 switch expression ([JEP 361](https://openjdk.org/jeps/361))

Test.java :
```java
public class Test {

    public void test() {
        var x = "foo";
        var y = switch (x) {
            case "foo" -> "foo2";
            default -> null;
        };
        System.out.println(y);
    }
}
```

checkstyle.xml : 
```xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="error"/>
    <property name="fileExtensions" value="java"/>
    <module name="TreeWalker">
        <module name="PreferMethodReference"/>
    </module>
</module>
```

```sh
$ java -cp sevntu-checks-1.42.0.jar:checkstyle-10.3.4-all.jar com.puppycrawl.tools.checkstyle.Main -c checkstyle.xml Test.java
```

Output :
```
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing Test.java
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:307)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
	at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:416)
	at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:339)
	at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:196)
	at com.puppycrawl.tools.checkstyle.Main.main(Main.java:131)
Caused by: java.lang.NullPointerException: Cannot invoke "com.puppycrawl.tools.checkstyle.api.DetailAST.getType()" because the return value of "com.puppycrawl.tools.checkstyle.api.DetailAST.getFirstChild()" is null
	at com.github.sevntu.checkstyle.checks.coding.PreferMethodReferenceCheck.getLambdaArgs(PreferMethodReferenceCheck.java:217)
	at com.github.sevntu.checkstyle.checks.coding.PreferMethodReferenceCheck.visitToken(PreferMethodReferenceCheck.java:201)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:336)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:407)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:274)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:155)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:98)
	at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:335)
	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:294)
	... 5 more
Checkstyle ends with 1 errors.
```

----

- Checkstyle [10.3.4](https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-10.3.4)
- Sventu checkstyle [1.42.0](https://github.com/sevntu-checkstyle/sevntu.checkstyle/releases/tag/1.42.0)
- Java :
```
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment (build 17.0.4+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.4+8-Ubuntu-120.04, mixed mode, sharing)
```

**Comment by rnveach** [comment]
> Checkstyle [10.3.4](https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-10.3.4)
Sventu checkstyle [1.42.0](https://github.com/sevntu-checkstyle/sevntu.checkstyle/releases/tag/1.42.0)

https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/49fa91f0755ab6de69da1ded281f0b5d079b7306/sevntu-checks/pom.xml#L19
Just so you are aware, sevntu has a compile time dependency against checkstyle 10.0 only right now. It cannot be guaranteed what will happen to have it work with a higher version of checkstyle than that.

**Comment by romani** [comment]
@jdussouillez, thanks a lot detailed report. 

Issue is approved, PR is welcome.

**Comment by rnveach** [comment]
Fix was merged
