### ISSUE TITLE
LogicConditionNeedOptimizationCheck: NPE on Java 17 file

### ISSUE THREAD

**Issue by rnveach** [sevntu-checkstyle/sevntu.checkstyle#922]
Identified at https://github.com/sevntu-checkstyle/sevntu.checkstyle/pull/921#issuecomment-1294182604 ,

````
$ cat TestClass.java
package com.puppycrawl.tools.checkstyle.checks.whitespace.operatorwrap;

public class InputOperatorWrapGuardedPatterns {
    String typeGuardAfterParenthesizedTrueSwitchStatement1(Object o) {
        switch (o) {
            case (Integer i)
                    && i == 0: o = String.valueOf(i); return "true"; // ok
            case ((Integer i)
                    && i == 2): o = String.valueOf(i); return "second"; // ok
            case Object x: return "any";
        }
    }

    String typeGuardAfterParenthesizedTrueSwitchExpression1(Object o) {
        return switch (o) {
            case (Integer i)
                    && i == 0: o = String.valueOf(i); yield "true"; // ok
            case ((Integer i)
                    && i == 2): o = String.valueOf(i); yield "second"; // ok
            case Object x: yield "any";
        };
    }

    String typeGuardAfterParenthesizedTrueIfStatement1(Object o) {
        if (o != null
                && o instanceof ((Integer i) // ok
                && i == 0)) { // ok
            return "true";
        } else if (o != null
                && o instanceof (((Integer i)  // ok
                && i == 2))  // ok
                && (o = i) != null) { // ok
            return "second";
        } else {
            return "any";
        }
    }

    String typeGuardAfterParenthesizedTrueSwitchStatement2(Object o) {
        switch (o) {
            case (Integer i) && // violation ''&&' should be on a new line.'
                    i == 0: o = String.valueOf(i); return "true";
            case ((Integer i) && // violation ''&&' should be on a new line.'
                    i == 2): o = String.valueOf(i); return "second";
            case Object x: return "any";
        }
    }

    String typeGuardAfterParenthesizedTrueSwitchExpression2(Object o) {
        return switch (o) {
            case (Integer i) && // violation ''&&' should be on a new line.'
                    i == 0: o = String.valueOf(i); yield "true";
            case ((Integer i) && // violation ''&&' should be on a new line.'
                    i == 2): o = String.valueOf(i); yield "second";
            case Object x: yield "any";
        };
    }

    String typeGuardAfterParenthesizedTrueIfStatement2(Object o) {
        if (o != null && // violation ''&&' should be on a new line.'
                o instanceof ((Integer i) && // violation ''&&' should be on a new line.'
                        i == 0)) {
            return "true";
        } else if (o != null && // violation ''&&' should be on a new line.'
                o instanceof (((Integer i) && // violation ''&&' should be on a new line.'
                        i == 2)) && // violation ''&&' should be on a new line.'
                (o = i) != null) {
            return "second";
        } else {
            return "any";
        }
    }
}


$ cat TestConfig.xml
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">

<module name="Checker">
    <property name="charset" value="UTF-8"/>

    <module name="TreeWalker">
<module name="com.github.sevntu.checkstyle.checks.coding.LogicConditionNeedOptimizationCheck"/>
    </module>
</module>

$ java -jar checkstyle-10.0-sevntu-1.42.0-all.jar -c TestConfig.xml TestClass.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing TestClass.java
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:305)
    at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
    at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:407)
    at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:330)
    at com.puppycrawl.tools.checkstyle.Main.execute(Main.java:189)
    at com.puppycrawl.tools.checkstyle.Main.main(Main.java:126)
Caused by: java.lang.NullPointerException
    at com.github.sevntu.checkstyle.checks.coding.LogicConditionNeedOptimizationCheck.getOperands(LogicConditionNeedOptimizationCheck.java:122)
    at com.github.sevntu.checkstyle.checks.coding.LogicConditionNeedOptimizationCheck.needOptimization(LogicConditionNeedOptimizationCheck.java:86)
    at com.github.sevntu.checkstyle.checks.coding.LogicConditionNeedOptimizationCheck.visitToken(LogicConditionNeedOptimizationCheck.java:69)
    at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:335)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:406)
    at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:273)
    at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:154)
    at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:87)
    at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:331)
    at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:292)
    ... 5 more
Checkstyle ends with 1 errors.
````

Expecting no exceptions.

**Comment by rnveach** [comment]
Fix was merged
